### ISSUE TITLE
Cannot able to see the retest id in the log

### ISSUE THREAD

**Issue by ambily-padman** [retest/recheck#740]
when the UI changes happen i am expecting  to see  the retestId in the log, but it only shows the expected and actual as bellow:
_

```
> 4 check(s) in 'de.retest.quickstarts.LoginTest' found the following difference(s):
> Test 'login' has 6 difference(s) in 4 state(s):
> 00 resulted in:
> 	Metadata Differences:
> 	  Please note that these differences do not affect the result and are not included in the difference count.
> 		url:
> 		  expected="<url expected>",
> 		    actual="<url actual>"
input (username) at 'html[1]/body[1]/form[1]/div[1]/input[1]':
		name:
		  expected="username",
		    actual="user", breaks="LoginTest.java:84"
```

_

**Comment by diba1013** [comment]
Hello @ambily-padman,

I apologize for taking so long to respond. I skimmed through the code and our [documentation](https://retest.de). The `retestId` is actually printed, however the documentation is not really clear and in some places inconsistent in that matter.

To clarify, the above report output consists of the following:

1. Structure representation
1. Metadata Differences
1. Element Differences
1. Attribute Differences

While the first two are solely to give some outlines and give hints on where/how the change occurred, the element differences are the important bit. It reads as follows:

```
type (retestid) at 'path':
    ... (some attribute differences)
```

1. `type`: The html tag name of the element (`<button>, <input>, ...`).
2. `retestid`: The stable virtual id (called `retestId`), which per [default](https://github.com/retest/recheck/blob/master/src/main/java/de/retest/recheck/ui/descriptors/idproviders/ElementCountingRetestIdProvider.java) looks for either `text`, `id`, `name` or `type` to be human readable. This can be [configured](https://docs.retest.de/recheck/usage/configuration/) with `RecheckOptionsBuilder#retestIdProvider(RetestIdProvider)`.
3. `path`: The recheck compatible XPath for that element.

Thus in your example, the retestId is the following `retestId=username`, which appears to be the name. Note that it will never change, despite the name changing in the displayed attribute difference.

I will try my best to update the documentation and necessary files to make this feature more clear and visible. Thank you for bringing this to our attention.

--- 

Since reading a wall of text is difficult, we try to keep the output as clear and concise as possible and therefore have decided against using something like 
`input (retestId=username) at '...'` at the expense that the user must familiarize themselves with the syntax.

However, we welcome any ideas, improvements and contributions to improve the readability of the report output.

**Comment by diba1013** [comment]
I have provided a [draft](retest/docs#116) for the documentation. Please feel free to provide any feedback.

If you do not have any additional remarks, I will consider this as resolved as soon as the PR is merged.

*Please note that there is always room for improvements for the documentation. If you think something is missing or needs adjustments, please feel free to contribute any changes.*
